-- Prepare structured campus navigation data for directory-style maps and future visual layouts.
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'COMPUTER_LAB';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'SCIENCE_LAB';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'ADMIN_OFFICE';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'STAFF_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'TEACHER_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'PRINCIPAL_OFFICE';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'FINANCE_OFFICE';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'EXAM_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'MEETING_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'SEMINAR_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'LECTURE_HALL';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'SPORTS_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'MEDICAL_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'COUNSELING_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'STORAGE';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'CAFETERIA';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'PRAYER_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'RECEPTION';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'SECURITY_ROOM';
ALTER TYPE "RoomType" ADD VALUE IF NOT EXISTS 'WASHROOM';

ALTER TABLE "Building"
  ADD COLUMN "landmark" TEXT,
  ADD COLUMN "directionsNote" TEXT,
  ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "mapX" DOUBLE PRECISION,
  ADD COLUMN "mapY" DOUBLE PRECISION,
  ADD COLUMN "mapWidth" DOUBLE PRECISION,
  ADD COLUMN "mapHeight" DOUBLE PRECISION;

UPDATE "Room"
SET "floor" = 'Unspecified'
WHERE "floor" IS NULL OR btrim("floor") = '';

ALTER TABLE "Room"
  ADD COLUMN "landmark" TEXT,
  ADD COLUMN "directionsNote" TEXT,
  ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "mapX" DOUBLE PRECISION,
  ADD COLUMN "mapY" DOUBLE PRECISION,
  ADD COLUMN "mapWidth" DOUBLE PRECISION,
  ADD COLUMN "mapHeight" DOUBLE PRECISION,
  ALTER COLUMN "floor" SET DEFAULT 'Unspecified',
  ALTER COLUMN "floor" SET NOT NULL;
