'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import useSWR from 'swr';
import { ArrowRightLeft, CheckCircle2, GraduationCap, Pause, Play, Repeat2, SkipForward, UserMinus } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { useGlobal } from '@/context/GlobalContext';
import { api } from '@/lib/api';
import { Cohort, CohortOfferingStatus, PaginatedResponse, Program, ProgramOffering, ProgramOfferingStatus, ProgramStageOfferingStatus, ProgramStatus, Role, Student, StudentProgramEnrollment, StudentProgramEnrollmentStatus, StudentProgressionOutcome, StudentProgressionPreview, StudentStageEnrollmentStatus } from '@/types';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { CustomSelect } from '@/components/ui/CustomSelect';
import { ErrorState } from '@/components/ui/ErrorState';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';
import { Loading } from '@/components/ui/Loading';
import { PageHeader, PageShell } from '@/components/ui/PageShell';

export default function StudentEnrollmentPage() {
    const { id: studentId } = useParams<{ id: string }>();
    const { token, user, loading } = useAuth();
    const { dispatch } = useGlobal();
    const router = useRouter();
    const canManage = user?.role === Role.ORG_ADMIN || user?.role === Role.SUB_ADMIN;
    const { data: student, error: studentError, isLoading: studentLoading, mutate: mutateStudent } = useSWR<Student>(token ? ['student', studentId] : null, () => api.org.getStudent(studentId, token!));
    const { data: history = [], mutate: mutateHistory } = useSWR<StudentProgramEnrollment[]>(token ? ['student-program-enrollments', studentId] : null, () => api.studentPrograms.list(studentId, token!));
    const { data: programs } = useSWR<PaginatedResponse<Program>>(token && canManage ? ['student-major-program-options'] : null, () => api.programs.getPrograms(token!, { limit: 1000, status: ProgramStatus.ACTIVE }));
    const [programId, setProgramId] = useState('');
    const [transferProgramId, setTransferProgramId] = useState('');
    const [entryStageId, setEntryStageId] = useState('');
    const [stageOfferingId, setStageOfferingId] = useState('');
    const [cohortOfferingId, setCohortOfferingId] = useState('');
    const [reason, setReason] = useState('');
    const [overrideReason, setOverrideReason] = useState('');
    const [error, setError] = useState('');
    const current = history.find((item) => [StudentProgramEnrollmentStatus.ADMITTED, StudentProgramEnrollmentStatus.ACTIVE, StudentProgramEnrollmentStatus.ON_HOLD].includes(item.status));
    const { data: progression, mutate: mutateProgression } = useSWR<StudentProgressionPreview>(token && current ? ['student-progression-preview', studentId, current.id] : null, () => api.studentPrograms.progressionPreview(studentId, current!.id, token!));
    const selectedProgramId = current?.programId || programId;
    const currentStageEnrollment = current?.stageEnrollments.find((stage) => stage.status === StudentStageEnrollmentStatus.IN_PROGRESS);
    const { data: selectedProgram } = useSWR<Program>(token && programId ? ['program', programId] : null, () => api.programs.getProgram(programId, token!));
    const { data: offerings = [] } = useSWR<ProgramOffering[]>(token && selectedProgramId ? ['program-offerings', { programId: selectedProgramId }] : null, () => api.programOfferings.list(token!, { programId: selectedProgramId }));
    const eligibleOfferingIds = new Set(progression?.offerings.map((offering) => offering.id) || []);
    const stageOfferings = offerings.filter((offering) => offering.status === ProgramOfferingStatus.OPEN).flatMap((offering) => offering.stageOfferings.filter((stage) => stage.status === ProgramStageOfferingStatus.OPEN && eligibleOfferingIds.has(stage.id)).map((stage) => ({ stage, offering })));
    const selectedStageOffering = stageOfferings.find((item) => item.stage.id === stageOfferingId);
    const { data: cohorts } = useSWR<PaginatedResponse<Cohort>>(token && selectedStageOffering ? ['cohorts', { academicCycleId: selectedStageOffering.offering.campusBinding!.academicCycleId, programId: selectedProgramId, limit: 1000 }] : null, () => api.cohorts.getCohorts(token!, { academicCycleId: selectedStageOffering!.offering.campusBinding!.academicCycleId, programId: selectedProgramId, limit: 1000 }));
    const cohortOfferings = useMemo(() => (cohorts?.data || []).flatMap((cohort) => (cohort.offerings || []).filter((offering) => offering.status === CohortOfferingStatus.ACTIVE && offering.programStageOfferingId === stageOfferingId).map((offering) => ({ offering, cohort }))), [cohorts?.data, stageOfferingId]);

    useEffect(() => { if (!loading && user && !canManage) router.replace('/users/students'); }, [canManage, loading, router, user]);
    const refresh = async () => { await Promise.all([mutateHistory(), mutateStudent(), mutateProgression()]); setReason(''); setOverrideReason(''); setError(''); };
    const run = async (id: string, operation: () => Promise<unknown>) => {
        dispatch({ type: 'UI_START_PROCESSING', payload: id });
        setError('');
        try { await operation(); await refresh(); dispatch({ type: 'TOAST_ADD', payload: { message: 'Enrollment updated', type: 'success' } }); }
        catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update enrollment'); }
        finally { dispatch({ type: 'UI_STOP_PROCESSING', payload: id }); }
    };

    if (studentError) return <ErrorState error={studentError} onRetry={() => mutateStudent()} />;
    if (studentLoading || !student) return <Loading className="h-full" text="Loading enrollment..." />;
    return <PageShell className="overflow-y-auto"><PageHeader title="Program Enrollment" description={`${student.user.name || student.user.email} · major, stage progression, and cycle placement`} icon={GraduationCap} breadcrumbs={[{ label: 'Students', href: '/users/students' }, { label: student.user.name || 'Student' }]} />
        {error && <div role="alert" className="rounded-md border border-danger/35 bg-danger/5 px-4 py-3 text-sm font-semibold text-danger">{error}</div>}
        {!current ? <section><Intro title="Assign major program" text="The selected program becomes the student's durable major and defines their main department across academic cycles." /><div className="space-y-5 rounded-lg border border-border/70 bg-card/75 p-5"><Field label="Program"><CustomSelect searchable value={programId} onChange={(id) => { setProgramId(id); setEntryStageId(''); }} options={(programs?.data || []).map((item) => ({ value: item.id, label: `${item.code} - ${item.name}` }))} /></Field>{selectedProgram && <Field label="Entry stage"><CustomSelect value={entryStageId} onChange={setEntryStageId} options={[{ value: '', label: 'First required stage' }, ...((selectedProgram.curriculumVersions?.find((item) => item.isDefaultForAdmissions) || selectedProgram.curriculumVersions?.[0])?.stages || []).map((item) => ({ value: item.id, label: `${item.code} - ${item.name}` }))]} /></Field>}<Button icon={GraduationCap} loadingId="program-admit" disabled={!programId} onClick={() => run('program-admit', () => api.studentPrograms.admit(studentId, { programId, entryStageId: entryStageId || undefined }, token!))}>Admit to program</Button></div></section> : <>
            <section><Intro title="Current major" text="This relationship survives cycle changes. Stage placements below record where the student is studying each part of the program." /><div className="flex flex-wrap items-center justify-between gap-4 rounded-lg border border-border/70 bg-card/75 p-5"><div><p className="text-base font-black">{current.program.code} - {current.program.name}</p><p className="mt-1 text-sm text-muted-foreground">{current.stageEnrollments.filter((item) => item.status === StudentStageEnrollmentStatus.COMPLETED || item.status === StudentStageEnrollmentStatus.SKIPPED).length} of {current.requiredStageCountSnapshot} stages resolved</p></div><div className="flex gap-2"><Badge variant={current.status === StudentProgramEnrollmentStatus.ACTIVE ? 'success' : 'neutral'}>{current.status}</Badge>{current.status === StudentProgramEnrollmentStatus.ON_HOLD ? <Button size="sm" icon={Play} loadingId="program-resume" onClick={() => run('program-resume', () => api.studentPrograms.resume(studentId, current.id, token!))}>Resume</Button> : <Button size="sm" variant="secondary" icon={Pause} loadingId="program-hold" disabled={!reason.trim()} onClick={() => run('program-hold', () => api.studentPrograms.hold(studentId, current.id, reason, token!))}>Hold</Button>}</div></div></section>
            <section><Intro title={currentStageEnrollment ? 'Choose the next offered stage' : 'Place in an offered stage'} text={currentStageEnrollment ? 'Select the target that will be activated atomically when the current stage is completed.' : 'Choose an eligible stage offering from an institute cycle. A matching cohort offering is optional.'} /><div className="space-y-5 rounded-lg border border-border/70 bg-card/75 p-5"><div className="rounded-md border border-border/70 bg-muted/25 px-4 py-3 text-sm"><span className="font-black">Recommendation: {progression?.recommendation || 'Loading'}</span>{progression?.blockers.map((blocker) => <p key={blocker.code} className="mt-1 text-muted-foreground">{blocker.message}</p>)}</div><Field label="Program stage offering"><CustomSelect searchable value={stageOfferingId} onChange={(id) => { setStageOfferingId(id); setCohortOfferingId(''); }} options={stageOfferings.map(({ stage, offering }) => ({ value: stage.id, label: `${offering.campusBinding?.academicCycle.code || offering.intakeName} - ${stage.programStage.name} (${stage.status})` }))} placeholder={stageOfferings.length ? 'Select eligible stage' : 'No eligible open stage offering'} /></Field><Field label="Cohort offering"><CustomSelect searchable value={cohortOfferingId} onChange={setCohortOfferingId} options={[{ value: '', label: 'No cohort' }, ...cohortOfferings.map(({ offering, cohort }) => ({ value: offering.id, label: `${cohort.code} - ${cohort.name}` }))]} disabled={!stageOfferingId} /></Field>{!currentStageEnrollment && <Button icon={Play} loadingId="stage-activate" disabled={!stageOfferingId} onClick={() => run('stage-activate', () => api.studentPrograms.activateStage(studentId, current.id, { programStageOfferingId: stageOfferingId, cohortOfferingId: cohortOfferingId || undefined, reason: reason || undefined }, token!))}>Activate stage</Button>}</div></section>
            <section><Intro title="Stage history" text="Each attempt is immutable history. Complete and advance atomically, skip, or repeat with an explicit reason." /><div className="divide-y divide-border/60 rounded-lg border border-border/70 bg-card/75">{current.stageEnrollments.map((stage) => { const repeatTarget = selectedStageOffering?.stage.programStageId === stage.programStageId ? selectedStageOffering.stage.id : undefined; const completesProgram = progression?.recommendation === StudentProgressionOutcome.COMPLETE && !stageOfferingId; return <div key={stage.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-sm font-black">{stage.stageCodeSnapshot} - {stage.stageNameSnapshot}</p><p className="text-xs text-muted-foreground">{stage.cycleCodeSnapshot} · Attempt {stage.attemptNumber}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={stage.status === StudentStageEnrollmentStatus.COMPLETED ? 'success' : 'neutral'} size="sm">{stage.status}</Badge>{stage.status === StudentStageEnrollmentStatus.IN_PROGRESS && <><Button size="icon" variant="ghost" icon={CheckCircle2} title={stageOfferingId ? 'Complete and advance to selected offering' : completesProgram ? 'Complete final stage and program' : 'Complete stage without placement'} disabled={!reason.trim() || Boolean(progression?.currentStageEvidence && !progression.currentStageEvidence.eligibleToComplete && !overrideReason.trim())} loadingId={`complete-${stage.id}`} onClick={() => run(`complete-${stage.id}`, () => stageOfferingId ? api.studentPrograms.advanceStage(studentId, current.id, stage.id, { reason, overrideReason: overrideReason || undefined, targetProgramStageOfferingId: stageOfferingId, cohortOfferingId: cohortOfferingId || undefined }, token!) : completesProgram ? api.studentPrograms.completeStageAndProgram(studentId, current.id, stage.id, { reason, overrideReason: overrideReason || undefined }, token!) : api.studentPrograms.completeStage(studentId, current.id, stage.id, { reason, overrideReason: overrideReason || undefined }, token!))} /><Button size="icon" variant="ghost" icon={SkipForward} title="Skip stage" disabled={!reason.trim()} loadingId={`skip-${stage.id}`} onClick={() => run(`skip-${stage.id}`, () => api.studentPrograms.skipStage(studentId, current.id, stage.id, { reason }, token!))} /><Button size="icon" variant="ghost" icon={Repeat2} title={repeatTarget ? 'Repeat into selected stage offering' : 'Select an open offering for this stage to repeat'} disabled={!reason.trim() || !repeatTarget} loadingId={`repeat-${stage.id}`} onClick={() => run(`repeat-${stage.id}`, () => api.studentPrograms.repeatStage(studentId, current.id, stage.id, { reason, targetProgramStageOfferingId: repeatTarget, cohortOfferingId: cohortOfferingId || undefined }, token!))} /></>}</div></div>; })}{!current.stageEnrollments.length && <p className="p-6 text-center text-sm text-muted-foreground">No stage attempts yet.</p>}</div></section>
            <Field label="Reason for progression or status changes"><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Required for hold, complete, skip, and repeat" /></Field>
            {progression?.currentStageEvidence && !progression.currentStageEvidence.eligibleToComplete && <Field label="Override reason"><Input value={overrideReason} onChange={(event) => setOverrideReason(event.target.value)} placeholder="Required to complete despite evidence blockers" /></Field>}
            <section><Intro title="Major lifecycle" text="Transfer preserves the source history. Withdrawal closes the major. Completion follows the program's configured completion policy." /><div className="space-y-4 rounded-lg border border-border/70 bg-card/75 p-5"><Field label="Transfer to program"><CustomSelect searchable value={transferProgramId} onChange={setTransferProgramId} options={(programs?.data || []).filter((program) => program.id !== current.programId).map((program) => ({ value: program.id, label: `${program.code} - ${program.name}` }))} placeholder="Select destination program" /></Field><div className="flex flex-wrap gap-2"><Button variant="secondary" icon={ArrowRightLeft} loadingId="program-transfer" disabled={!transferProgramId || !reason.trim()} onClick={() => run('program-transfer', () => api.studentPrograms.transfer(studentId, { programId: transferProgramId, reason }, token!))}>Transfer major</Button><Button variant="danger" icon={UserMinus} loadingId="program-withdraw" disabled={!reason.trim()} onClick={() => run('program-withdraw', () => api.studentPrograms.withdraw(studentId, current.id, { reason }, token!))}>Withdraw</Button><Button icon={CheckCircle2} loadingId="program-complete" disabled={!reason.trim() || (!progression?.canCompleteProgram && !progression?.blockers.some((blocker) => blocker.code === 'MANUAL_COMPLETION'))} onClick={() => run('program-complete', () => api.studentPrograms.complete(studentId, current.id, { reason }, token!))}>Complete program</Button></div></div></section>
        </>}
    </PageShell>;
}

function Intro({ title, text }: { title: string; text: string }) { return <div className="mb-3"><h2 className="text-base font-black">{title}</h2><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{text}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
