export interface AIFlowStep {
  label: string;
  detail: string;
}

export interface AIFlowDefinition {
  id: string;
  title: string;
  category: string;
  summary: string;
  roles: string[];
  tags: string[];
  routes: Array<{ label: string; href: string }>;
  prerequisites: string[];
  steps: AIFlowStep[];
  warnings?: string[];
  relatedDocs?: string[];
}

export interface AIFlowSearchEntry {
  id: string;
  title: string;
  category: string;
  summary: string;
  roles: string[];
  tags: string[];
  routes: Array<{ label: string; href: string }>;
  prerequisites: string[];
  steps: AIFlowStep[];
  warnings: string[];
  relatedDocs: string[];
  bodyText: string;
  tagText: string;
  routeText: string;
}

export const aiFlows: AIFlowDefinition[] = [
  {
    id: 'workspace-onboarding',
    title: 'Workspace onboarding',
    category: 'Setup',
    summary: 'Bring a new organization workspace from registration to usable academic operations.',
    roles: ['ORG_ADMIN'],
    tags: ['setup', 'workspace', 'organization', 'getting started', 'quick start'],
    routes: [
      { label: 'Overview', href: '/overview' },
      { label: 'Settings', href: '/settings' },
    ],
    prerequisites: ['Organization account exists and the signed-in user is the Org Admin.'],
    steps: [
      { label: 'Review workspace', detail: 'Open Overview to confirm the organization dashboard loads and the active role is correct.' },
      { label: 'Configure identity', detail: 'Open Settings and complete organization profile, contact details, branding, and finance defaults where applicable.' },
      { label: 'Create academic basics', detail: 'Create GPA policy, academic cycle, courses, cohorts, sections, teachers, and students in that order when starting from an empty workspace.' },
      { label: 'Verify access', detail: 'Use role-aware dashboards and lists to confirm staff and learners see the expected modules.' },
    ],
    warnings: ['Skipping setup order can create empty dropdowns, missing timetable records, or incorrect transcript context.'],
    relatedDocs: ['/docs/quick-start', '/docs/school-setup-workflow', '/docs/settings'],
  },
  {
    id: 'organization-settings',
    title: 'Organization settings update',
    category: 'Administration',
    summary: 'Update organization profile, appearance, security, finance defaults, and Copilot settings.',
    roles: ['ORG_ADMIN'],
    tags: ['settings', 'organization profile', 'branding', 'security', 'finance defaults', 'ai settings'],
    routes: [{ label: 'Settings', href: '/settings' }],
    prerequisites: ['Signed-in user is Org Admin.'],
    steps: [
      { label: 'Open settings', detail: 'Open Settings from the sidebar.' },
      { label: 'Select section', detail: 'Use the relevant settings tab or panel for organization profile, appearance, finance defaults, security, or EduVerse Copilot.' },
      { label: 'Update fields', detail: 'Edit only the fields that should change and review required values before saving.' },
      { label: 'Save and verify', detail: 'Save changes, then refresh affected dashboards or documents if the change should appear elsewhere.' },
    ],
    warnings: ['Settings affect organization-wide behavior and should not be used for student enrollment or course placement workflows.'],
    relatedDocs: ['/docs/settings'],
  },
  {
    id: 'role-account-create',
    title: 'Role account creation',
    category: 'People',
    summary: 'Create staff, learner, guardian, sub-admin, and finance-manager accounts from the appropriate People area.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['users', 'accounts', 'add user', 'create account', 'teacher', 'student', 'guardian', 'sub admin', 'finance manager'],
    routes: [
      { label: 'Users', href: '/users' },
      { label: 'Students', href: '/users/students' },
      { label: 'Teachers', href: '/users/teachers' },
      { label: 'Guardians', href: '/users/guardians' },
    ],
    prerequisites: ['Creator has permission for the target role.', 'Required identity and login details are available.'],
    steps: [
      { label: 'Open people area', detail: 'Open Users, then choose the target account area such as Students, Teachers, Guardians, Sub Admins, or Finance Managers.' },
      { label: 'Start creation', detail: 'Click the Add action for that account type.' },
      { label: 'Fill identity', detail: 'Enter full name, email, password, status, and role-specific fields.' },
      { label: 'Add scope', detail: 'Assign departments, sections, guardian links, or finance scope where that role requires placement.' },
      { label: 'Save account', detail: 'Save the form and verify the new account appears in the relevant list.' },
    ],
    warnings: ['Use the dedicated role area; do not create academic placement from Settings.'],
    relatedDocs: ['/docs/roles-permissions', '/docs/students', '/docs/teachers'],
  },
  {
    id: 'student-record-create',
    title: 'Student record creation',
    category: 'People',
    summary: 'Create a student login and profile record before cohort or section placement.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['student', 'add student', 'create student', 'new learner', 'registration number', 'roll number'],
    routes: [
      { label: 'Students', href: '/users/students' },
      { label: 'Add Student', href: '/users/students/add' },
    ],
    prerequisites: ['Student email, password, registration number, roll number, major/program, and gender are available.'],
    steps: [
      { label: 'Open students', detail: 'Open Users, then Students, or go directly to /users/students.' },
      { label: 'Click Add Student', detail: 'Use the Add Student button in the Students page header.' },
      { label: 'Fill account fields', detail: 'Enter Full Name, Account Email, Login Password, Registration Number, Roll Number, Admission Date, Student Status, Major / Program, and Primary Department if used.' },
      { label: 'Fill profile fields', detail: 'Add guardian, department, expected graduation, phone, emergency, blood group, address, and other profile fields where needed.' },
      { label: 'Save record', detail: 'Save the student. EduVerse creates the student record and login account, then returns to the Students list.' },
    ],
    warnings: ['Creating a student record does not automatically enroll the student in a course unless cohort placement or section enrollment is also configured.'],
    relatedDocs: ['/docs/students'],
  },
  {
    id: 'student-placement-enrollment',
    title: 'Student placement and enrollment',
    category: 'People',
    summary: 'Place a student into cohorts or sections after the student record exists.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['student enrollment', 'enroll student', 'cohort placement', 'section enrollment', 'course enrollment'],
    routes: [
      { label: 'Students', href: '/users/students' },
      { label: 'Manage Enrollment', href: '/users/students' },
    ],
    prerequisites: ['Student exists and is Active.', 'Target section exists in the correct academic cycle.', 'Creator can manage the student and section department scope.'],
    steps: [
      { label: 'Open student', detail: 'Open Users > Students, find the student, then choose Manage Enrollment from row actions or the Manage link in the student edit form.' },
      { label: 'Choose cohort if needed', detail: 'For group placement, search at least two characters in Cohort Placement, select a cohort, then click Apply Cohort.' },
      { label: 'Choose section if needed', detail: 'For individual class placement, search at least two characters in Add Section, select the section for the course, then click Enroll.' },
      { label: 'Review warnings', detail: 'Read capacity and no-schedule warnings. They warn but do not automatically block enrollment.' },
      { label: 'Verify placement', detail: 'Confirm the cohort and Section Enrollments list show the expected records.' },
    ],
    warnings: ['Students enroll into sections, not directly into course records.', 'Deleted and alumni students cannot be enrolled.'],
    relatedDocs: ['/docs/students', '/docs/courses-sections', '/docs/cohorts-reassignment'],
  },
  {
    id: 'guardian-linking',
    title: 'Guardian account linking',
    category: 'People',
    summary: 'Create guardian accounts and link them to student records.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['guardian', 'parent', 'linked student', 'student guardian'],
    routes: [
      { label: 'Guardians', href: '/users/guardians' },
      { label: 'Students', href: '/users/students' },
    ],
    prerequisites: ['Guardian account exists or can be created.', 'Student record exists.'],
    steps: [
      { label: 'Create guardian', detail: 'Open Users > Guardians and add the guardian account if it does not exist.' },
      { label: 'Open student', detail: 'Open the student edit form for the learner who should be linked.' },
      { label: 'Select guardian', detail: 'Use the Linked Guardian field and relationship label in the student profile form.' },
      { label: 'Save', detail: 'Save the student record and verify the guardian can see the linked-student portal context.' },
    ],
    warnings: ['Guardians only see linked students; linking the wrong guardian exposes student context to the wrong account.'],
    relatedDocs: ['/docs/guardian-guide', '/docs/students'],
  },
  {
    id: 'teacher-manager-assignment',
    title: 'Teacher or manager assignment',
    category: 'People',
    summary: 'Create teacher/manager accounts and connect them to departments, sections, schedules, and workload.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['teacher', 'manager', 'faculty', 'assign teacher', 'section teacher'],
    routes: [
      { label: 'Teachers and Managers', href: '/users/teachers' },
      { label: 'Sections', href: '/sections' },
    ],
    prerequisites: ['Teacher or manager account exists.', 'Sections exist for the relevant courses and cycles.'],
    steps: [
      { label: 'Create account', detail: 'Open Users > Teachers and add the teacher or manager with role-specific profile details.' },
      { label: 'Set scope', detail: 'Assign department scope where the role uses department-scoped access.' },
      { label: 'Assign sections', detail: 'Open the relevant section and add the teacher to the section teacher list.' },
      { label: 'Assign schedules', detail: 'Create or update schedule slots and choose the teacher responsible for each slot.' },
      { label: 'Verify workload', detail: 'Review sections and timetable to confirm the teacher or manager sees the correct work.' },
    ],
    warnings: ['A teacher assigned to a section is not automatically assigned to every schedule slot unless the schedule selects that teacher.'],
    relatedDocs: ['/docs/teachers', '/docs/timetable'],
  },
  {
    id: 'academic-cycle-create',
    title: 'Academic cycle setup',
    category: 'Academics',
    summary: 'Create terms, semesters, sessions, or academic years before cohorts and sections depend on them.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['academic cycle', 'semester', 'term', 'session', 'year'],
    routes: [{ label: 'Academic Cycles', href: '/academic-cycles' }],
    prerequisites: ['GPA policy exists when the cycle should use a specific grading policy.'],
    steps: [
      { label: 'Open cycles', detail: 'Open Academic Cycles from the academic setup area.' },
      { label: 'Create cycle', detail: 'Click Add Academic Cycle and enter name, code, start date, end date, status, and GPA policy if needed.' },
      { label: 'Activate if current', detail: 'Mark the correct cycle active when it should drive current-cycle lists and workflows.' },
      { label: 'Build dependent records', detail: 'Create cohorts and sections under the cycle after saving it.' },
    ],
    warnings: ['Changing cycle policy is restricted after finalized grades exist.'],
    relatedDocs: ['/docs/academic-cycles', '/docs/gpa-policies'],
  },
  {
    id: 'gpa-policy-manage',
    title: 'GPA policy management',
    category: 'Academic Settings',
    summary: 'Create, validate, preview, and assign GPA policies before grade finalization.',
    roles: ['ORG_ADMIN'],
    tags: ['gpa policy', 'grade rules', 'transcript', 'grade points', 'cgpa'],
    routes: [{ label: 'GPA Policies', href: '/gpa-policies' }],
    prerequisites: ['Organization grading rules are known.', 'Grade boundaries and scale are ready.'],
    steps: [
      { label: 'Open GPA policies', detail: 'Open GPA Policies from academic settings.' },
      { label: 'Create policy', detail: 'Enter policy name, scale, method, rounding, and grade rules.' },
      { label: 'Validate ranges', detail: 'Make sure grade rules cover 0-100 without gaps or overlaps and stay within the scale.' },
      { label: 'Preview', detail: 'Use preview values near boundaries to confirm letters and grade points.' },
      { label: 'Assign', detail: 'Set the default policy or assign a policy to an academic cycle before grades are finalized.' },
    ],
    warnings: ['Do not change policy assumptions after finalized grades exist for the cycle.'],
    relatedDocs: ['/docs/gpa-policies', '/docs/academic-cycles'],
  },
  {
    id: 'course-create',
    title: 'Course creation',
    category: 'Academics',
    summary: 'Create the subject record that sections, assessments, materials, and transcripts use.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['course', 'subject', 'credit hours', 'create course'],
    routes: [
      { label: 'Courses', href: '/courses' },
      { label: 'Add Course', href: '/courses/create' },
    ],
    prerequisites: ['Department exists if the course should be department-scoped.'],
    steps: [
      { label: 'Open courses', detail: 'Open Courses and click Add Course.' },
      { label: 'Fill details', detail: 'Enter course name, code, department, credit hours, and description where applicable.' },
      { label: 'Save course', detail: 'Save the subject record.' },
      { label: 'Create sections', detail: 'Create one or more sections for actual class delivery in a specific academic cycle.' },
    ],
    warnings: ['Do not create duplicate courses for separate class groups; create separate sections under one course.'],
    relatedDocs: ['/docs/courses-sections'],
  },
  {
    id: 'section-create',
    title: 'Section creation',
    category: 'Academics',
    summary: 'Create an enrollable class instance for a course and academic cycle.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['section', 'class', 'create section', 'teacher assignment', 'student assignment'],
    routes: [
      { label: 'Sections', href: '/sections' },
      { label: 'Add Section', href: '/sections/create' },
    ],
    prerequisites: ['Course exists.', 'Academic cycle exists.', 'Teachers, cohorts, rooms, and students exist if they should be attached.'],
    steps: [
      { label: 'Open sections', detail: 'Open Sections and click Add Section.' },
      { label: 'Choose academics', detail: 'Select course and academic cycle, then enter section name, code, and color.' },
      { label: 'Attach people', detail: 'Assign teachers, cohort, or direct students as needed.' },
      { label: 'Set room', detail: 'Choose a default room if the section usually meets there.' },
      { label: 'Save section', detail: 'Save, then manage schedules, materials, assessments, attendance, and enrollment from the section or student workflows.' },
    ],
    warnings: ['A section is what students attend; course records alone are not enrollable.'],
    relatedDocs: ['/docs/courses-sections'],
  },
  {
    id: 'cohort-manage',
    title: 'Cohort management',
    category: 'Academics',
    summary: 'Group students and attach cohort sections for bulk enrollment.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['cohort', 'batch', 'student group', 'bulk enrollment'],
    routes: [{ label: 'Cohorts', href: '/cohorts' }],
    prerequisites: ['Academic cycle exists.', 'Students and sections exist before assignment.'],
    steps: [
      { label: 'Open cohorts', detail: 'Open Cohorts and create or edit a cohort.' },
      { label: 'Define cohort', detail: 'Enter name, code, academic cycle, and description.' },
      { label: 'Assign students', detail: 'Select students who belong to the group.' },
      { label: 'Assign sections', detail: 'Attach sections the whole cohort should take.' },
      { label: 'Review enrollments', detail: 'Verify cohort-sourced enrollments and exclusions after saving.' },
    ],
    warnings: ['Changing cohort membership can add or remove cohort-sourced section enrollments.'],
    relatedDocs: ['/docs/cohorts-reassignment'],
  },
  {
    id: 'schedule-create',
    title: 'Schedule creation',
    category: 'Academics',
    summary: 'Create official or ad-hoc timetable slots for section teaching activity.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['schedule', 'timetable', 'class time', 'teacher schedule', 'room schedule'],
    routes: [
      { label: 'Schedules', href: '/schedules' },
      { label: 'Sections', href: '/sections' },
    ],
    prerequisites: ['Section exists.', 'Teacher is assigned or available.', 'Room exists if structured room conflict checks are needed.'],
    steps: [
      { label: 'Open schedules', detail: 'Open Schedules or the schedule area for a section.' },
      { label: 'Choose section', detail: 'Select the section, schedule type, day or date, start time, and end time.' },
      { label: 'Choose teacher and room', detail: 'Select the responsible teacher and room for the slot.' },
      { label: 'Review conflicts', detail: 'Check teacher, room, and student overlap warnings before saving.' },
      { label: 'Save slot', detail: 'Save the schedule and verify it appears in timetable views.' },
    ],
    warnings: ['A section default room is only a suggestion; the schedule room is the actual timetable location.'],
    relatedDocs: ['/docs/timetable', '/docs/campus-navigation'],
  },
  {
    id: 'attendance-record',
    title: 'Attendance recording',
    category: 'Academics',
    summary: 'Record attendance against scheduled class activity.',
    roles: ['TEACHER'],
    tags: ['attendance', 'mark attendance', 'present', 'absent', 'late'],
    routes: [{ label: 'Attendance', href: '/attendance' }],
    prerequisites: ['Section has a schedule.', 'Students are enrolled.', 'Teacher owns the selected schedule slot.'],
    steps: [
      { label: 'Open attendance', detail: 'Open Attendance and choose the section, date, and schedule slot.' },
      { label: 'Review list', detail: 'Confirm enrolled students and class context before marking.' },
      { label: 'Mark statuses', detail: 'Set each student as present, absent, late, excused, or the available organization status.' },
      { label: 'Save attendance', detail: 'Save the sheet and review any confirmation or correction state.' },
      { label: 'Review risk', detail: 'Use attendance summaries to identify repeated absence or weak attendance patterns.' },
    ],
    warnings: ['Admins can review broad attendance coverage but attendance marking is schedule-owner scoped.'],
    relatedDocs: ['/docs/attendance', '/docs/timetable'],
  },
  {
    id: 'material-publish',
    title: 'Course material publishing',
    category: 'Academics',
    summary: 'Share files, links, or notes with a section.',
    roles: ['TEACHER', 'ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['materials', 'course material', 'files', 'links', 'section content'],
    routes: [{ label: 'Sections', href: '/sections' }],
    prerequisites: ['Section exists and the actor can access it.'],
    steps: [
      { label: 'Open section', detail: 'Open the target section detail page.' },
      { label: 'Open materials', detail: 'Use the course materials area for that section.' },
      { label: 'Add material', detail: 'Create a material with title, description, file, or link as appropriate.' },
      { label: 'Save and verify', detail: 'Save and verify the item is visible in the section material list.' },
    ],
    warnings: ['Only share files and links that are safe and appropriate for the section audience.'],
    relatedDocs: ['/docs/materials', '/docs/files-attachments'],
  },
  {
    id: 'assessment-create',
    title: 'Assessment creation',
    category: 'Academics',
    summary: 'Create quizzes, assignments, exams, or other graded work for a section.',
    roles: ['TEACHER', 'ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['assessment', 'assignment', 'quiz', 'exam', 'due date', 'submissions'],
    routes: [{ label: 'Sections', href: '/sections' }],
    prerequisites: ['Section exists.', 'Teacher or staff actor can manage the section.'],
    steps: [
      { label: 'Open section', detail: 'Open the section and go to assessments.' },
      { label: 'Create assessment', detail: 'Enter title, type, total marks, due date, weight, instructions, and submission settings.' },
      { label: 'Attach files if needed', detail: 'Upload supporting files only when they are needed for the work.' },
      { label: 'Save assessment', detail: 'Save and verify it appears for the section and eligible students.' },
    ],
    warnings: ['Due dates and submission settings should match how students are expected to turn in work.'],
    relatedDocs: ['/docs/assessments-grading', '/docs/submissions'],
  },
  {
    id: 'student-submission',
    title: 'Student submission',
    category: 'Learning',
    summary: 'Submit work to an assessment from the student portal.',
    roles: ['STUDENT'],
    tags: ['submission', 'student work', 'assignment', 'upload', 'link'],
    routes: [{ label: 'Student Portal', href: '/student/{userId}' }],
    prerequisites: ['Student is enrolled in the section.', 'Assessment allows submissions.'],
    steps: [
      { label: 'Open assessment', detail: 'Open the assessment from the student portal or section context.' },
      { label: 'Review instructions', detail: 'Check due date, requirements, file rules, and any teacher instructions.' },
      { label: 'Add work', detail: 'Provide a file, link, written response, or the required combination.' },
      { label: 'Submit', detail: 'Submit and verify the status changed to submitted.' },
    ],
    warnings: ['Late or missing work may affect grades depending on school policy.'],
    relatedDocs: ['/docs/submissions', '/docs/student-guide'],
  },
  {
    id: 'grading-workflow',
    title: 'Grading workflow',
    category: 'Academics',
    summary: 'Enter, review, publish, and finalize grades for assessments.',
    roles: ['TEACHER', 'ORG_MANAGER'],
    tags: ['grading', 'gradebook', 'marks', 'publish grades', 'finalize grades'],
    routes: [
      { label: 'Grades', href: '/grades' },
      { label: 'Sections', href: '/sections' },
    ],
    prerequisites: ['Assessment exists.', 'Students are enrolled.', 'Actor can grade the section.'],
    steps: [
      { label: 'Open gradebook', detail: 'Open Grades or the assessment gradebook for the section.' },
      { label: 'Enter marks', detail: 'Enter marks, status, and feedback for each student.' },
      { label: 'Review constraints', detail: 'Check total marks, minimum marks, zero rules, and student rows before saving.' },
      { label: 'Save or publish', detail: 'Save draft grades or publish grades when they should be visible to students.' },
      { label: 'Finalize when ready', detail: 'Use finalization only after official review because finalized grades feed transcripts.' },
    ],
    warnings: ['Finalized grades are treated as official and may lock GPA policy choices for the cycle.'],
    relatedDocs: ['/docs/gradebook', '/docs/assessments-grading'],
  },
  {
    id: 'grade-finalization',
    title: 'Grade finalization',
    category: 'Academics',
    summary: 'Review and finalize grades for official transcript readiness.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER'],
    tags: ['grade finalization', 'finalize grades', 'official grades', 'transcripts'],
    routes: [{ label: 'Grade Finalization', href: '/grade-finalization' }],
    prerequisites: ['Grades have been entered and reviewed.', 'Correct GPA policy is assigned to the academic cycle.'],
    steps: [
      { label: 'Open finalization', detail: 'Open Grade Finalization.' },
      { label: 'Filter scope', detail: 'Choose cycle, course, section, department, or other available filters.' },
      { label: 'Review grades', detail: 'Check marks, student names, course context, and grade status.' },
      { label: 'Finalize', detail: 'Finalize only when the records are official and ready for transcript use.' },
    ],
    warnings: ['Finalization can restrict later GPA policy changes and should not be used as a routine save action.'],
    relatedDocs: ['/docs/end-of-term-workflow', '/docs/gpa-policies'],
  },
  {
    id: 'transcript-generate',
    title: 'Transcript generation',
    category: 'Academics',
    summary: 'Generate student or cycle transcript reports from finalized academic records.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER', 'STUDENT'],
    tags: ['transcript', 'gpa', 'cgpa', 'report card', 'academic record'],
    routes: [{ label: 'Transcripts', href: '/transcripts' }],
    prerequisites: ['Relevant grades are finalized.', 'Academic cycle and GPA policy are configured.'],
    steps: [
      { label: 'Open transcripts', detail: 'Open Transcripts from the academic area or student portal.' },
      { label: 'Choose scope', detail: 'Select student and cycle, or use the available cycle report view.' },
      { label: 'Generate report', detail: 'Review marks, letters, GPA, CGPA, credit hours, and cycle context.' },
      { label: 'Export if needed', detail: 'Download or share only according to role and privacy rules.' },
    ],
    warnings: ['Transcripts depend on finalized grades and the GPA policy selected for each cycle.'],
    relatedDocs: ['/docs/transcripts', '/docs/gpa-policies'],
  },
  {
    id: 'reassignment-workflow',
    title: 'Student cohort reassignment',
    category: 'Academics',
    summary: 'Move students between cohorts or sections, including next-cycle, same-cycle, and demotion moves.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['reassignment', 'next cycle', 'cohort move', 'section move'],
    routes: [{ label: 'Reassignment', href: '/reassignment' }],
    prerequisites: ['Target cycle and destination cohort or section exist.', 'Transcript and final grade review is complete where required.'],
    steps: [
      { label: 'Prepare destination', detail: 'Create the needed academic cycle, cohorts, and sections before reassignment.' },
      { label: 'Open reassignment', detail: 'Open the Reassignment tool.' },
      { label: 'Select source and destination', detail: 'Choose source cohort or section, then choose the destination cohort or section.' },
      { label: 'Review students', detail: 'Exclude any students who should stay behind before confirming.' },
      { label: 'Reassign', detail: 'Run reassignment and review reassigned, skipped, and excluded counts.' },
    ],
    warnings: ['Reassignment changes current placement while preserving historical academic data. Review before confirming.'],
    relatedDocs: ['/docs/end-of-term-workflow', '/docs/cohorts-reassignment'],
  },
  {
    id: 'evaluation-window-manage',
    title: 'Evaluation window management',
    category: 'Quality',
    summary: 'Open and review teacher or course evaluation windows.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER'],
    tags: ['evaluations', 'feedback', 'teacher review', 'course review', 'window'],
    routes: [{ label: 'Evaluations', href: '/evaluations' }],
    prerequisites: ['Eligible academic history exists.', 'Evaluation scope is known.'],
    steps: [
      { label: 'Open evaluations', detail: 'Open Evaluations and choose windows or summaries.' },
      { label: 'Create window', detail: 'Set evaluation type, scope, academic cycle, dates, and eligible audience.' },
      { label: 'Publish window', detail: 'Open the window when students should submit feedback.' },
      { label: 'Review summary', detail: 'Review aggregate ratings and trends without exposing confidential reviewer identity.' },
    ],
    warnings: ['Do not expose raw confidential responses or reviewer identities in summaries.'],
    relatedDocs: ['/docs/evaluations-feedback'],
  },
  {
    id: 'preference-window-manage',
    title: 'Preference window management',
    category: 'Operations',
    summary: 'Collect course or section preferences and optionally enroll from results.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER'],
    tags: ['preference window', 'poll', 'course choice', 'section choice', 'ranked preference'],
    routes: [{ label: 'Preference Windows', href: '/preference-windows' }],
    prerequisites: ['Options already exist as courses or sections.', 'Audience scope is known.'],
    steps: [
      { label: 'Open preference windows', detail: 'Open Preference Windows and start a new poll/window.' },
      { label: 'Choose kind', detail: 'Select course choice or section choice and configure dates.' },
      { label: 'Add audience and options', detail: 'Select target students, cohorts, courses, or sections, then add eligible options.' },
      { label: 'Publish and monitor', detail: 'Collect responses and review results.' },
      { label: 'Enroll if needed', detail: 'For section-choice windows, permitted admins can enroll students into selected sections from results.' },
    ],
    warnings: ['Preference windows do not create courses, sections, teachers, rooms, or schedules.'],
    relatedDocs: ['/docs/preference-windows'],
  },
  {
    id: 'finance-structure-manage',
    title: 'Finance structure management',
    category: 'Finance',
    summary: 'Create reusable fee, payroll, income, or expense structures and assign them to targets.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'FINANCE_MANAGER'],
    tags: ['finance structure', 'fees', 'salary', 'payroll', 'billing'],
    routes: [{ label: 'Fee Structures', href: '/finance/structures' }],
    prerequisites: ['Finance access is enabled for the actor.', 'Assignment target and amount rules are known.'],
    steps: [
      { label: 'Open structures', detail: 'Open Finance > Structures.' },
      { label: 'Create structure', detail: 'Enter structure name, type, amount, schedule, and assignment rules.' },
      { label: 'Assign targets', detail: 'Attach students, staff, sections, cohorts, courses, or other supported entities.' },
      { label: 'Generate entries', detail: 'Generate finance entries when the structure should create payable or receivable records.' },
    ],
    warnings: ['Changing structures can affect generated entries depending on update rules.'],
    relatedDocs: ['/docs/finance'],
  },
  {
    id: 'finance-entry-payment',
    title: 'Finance entry and payment handling',
    category: 'Finance',
    summary: 'Create, review, mark, confirm, cancel, or reverse finance entries and transactions.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'FINANCE_MANAGER'],
    tags: ['finance entry', 'payment', 'claim', 'confirm payment', 'transaction'],
    routes: [
      { label: 'Finance Entries', href: '/finance/entries' },
      { label: 'Transactions', href: '/finance/transactions' },
    ],
    prerequisites: ['Finance entry exists or required manual entry details are available.'],
    steps: [
      { label: 'Open entries', detail: 'Open Finance > Entries and find or create the entry.' },
      { label: 'Review amount', detail: 'Check title, student or staff assignment, due date, expected amount, paid amount, and status.' },
      { label: 'Record payment', detail: 'Mark paid or confirm a payment claim after checking reference, receipt, amount, and payer.' },
      { label: 'Audit transaction', detail: 'Use transactions and audit logs to review confirmed financial changes.' },
    ],
    warnings: ['Confirming payments changes balances and transaction history; check evidence before accepting.'],
    relatedDocs: ['/docs/finance', '/docs/fees'],
  },
  {
    id: 'payroll-review',
    title: 'Payroll review',
    category: 'Finance',
    summary: 'Review staff payroll and teacher finance context.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'FINANCE_MANAGER', 'TEACHER'],
    tags: ['payroll', 'salary', 'teacher payroll', 'finance manager'],
    routes: [
      { label: 'Payroll', href: '/finance/payroll' },
      { label: 'My Payroll', href: '/finance/my-payroll' },
    ],
    prerequisites: ['Finance structures or entries exist for the staff member.'],
    steps: [
      { label: 'Open payroll', detail: 'Finance staff open payroll views; teachers open My Payroll where available.' },
      { label: 'Filter records', detail: 'Use staff, date, status, or structure filters where available.' },
      { label: 'Review totals', detail: 'Check generated entries, paid amounts, pending balances, and transaction history.' },
      { label: 'Resolve issues', detail: 'Correct structures, entries, or transactions through the finance workflow when needed.' },
    ],
    warnings: ['Payroll visibility depends on finance role and self-view boundaries.'],
    relatedDocs: ['/docs/finance', '/docs/finance-manager-guide'],
  },
  {
    id: 'announcement-send',
    title: 'Announcement publishing',
    category: 'Communication',
    summary: 'Publish announcements to organization, role, course, section, cohort, or global audiences.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER', 'TEACHER'],
    tags: ['announcement', 'notice', 'broadcast', 'audience'],
    routes: [{ label: 'Announcements', href: '/announcements' }],
    prerequisites: ['Audience is known.', 'Message content is appropriate for the target group.'],
    steps: [
      { label: 'Open announcements', detail: 'Open Announcements and start a new announcement.' },
      { label: 'Choose audience', detail: 'Select organization, role, course, section, cohort, or other available target.' },
      { label: 'Write content', detail: 'Enter title, body, priority, optional action link, and timing where available.' },
      { label: 'Publish', detail: 'Publish and verify the announcement appears for the intended audience.' },
    ],
    warnings: ['Avoid sharing private student information unless the selected audience should see it.'],
    relatedDocs: ['/docs/announcements'],
  },
  {
    id: 'chat-start',
    title: 'Chat conversation',
    category: 'Communication',
    summary: 'Start direct or group chat with permitted users.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER', 'FINANCE_MANAGER', 'TEACHER', 'STUDENT', 'GUARDIAN'],
    tags: ['chat', 'message', 'group chat', 'direct message'],
    routes: [{ label: 'Chat', href: '/chat' }],
    prerequisites: ['Recipient or group audience is permitted by role boundaries.'],
    steps: [
      { label: 'Open chat', detail: 'Open Chat and choose new direct or group conversation.' },
      { label: 'Select people', detail: 'Search or choose participants from permitted presets and role-scoped lists.' },
      { label: 'Write message', detail: 'Enter the message and add attachments only if needed.' },
      { label: 'Send and manage', detail: 'Send, then use message actions or chat settings according to permission.' },
    ],
    warnings: ['Managers, teachers, students, and guardians have role-scoped contact boundaries.'],
    relatedDocs: ['/docs/chat', '/docs/communication'],
  },
  {
    id: 'mail-thread',
    title: 'Mail thread workflow',
    category: 'Communication',
    summary: 'Create and manage structured school mail threads with status and assignment.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER', 'FINANCE_MANAGER', 'TEACHER', 'STUDENT', 'GUARDIAN'],
    tags: ['mail', 'thread', 'ticket', 'support', 'status'],
    routes: [{ label: 'Mail', href: '/mail' }],
    prerequisites: ['Recipient or target area is permitted for the signed-in role.'],
    steps: [
      { label: 'Open mail', detail: 'Open Mail and create a new thread.' },
      { label: 'Choose participants', detail: 'Select recipient, category, priority, and subject.' },
      { label: 'Write message', detail: 'Add message text and relevant attachments.' },
      { label: 'Track status', detail: 'Use thread status, assignment, and replies until the issue is resolved.' },
    ],
    warnings: ['Mail can carry sensitive records; keep attachments relevant and safe.'],
    relatedDocs: ['/docs/mail', '/docs/support-contact'],
  },
  {
    id: 'csv-import',
    title: 'CSV import',
    category: 'Setup',
    summary: 'Import supported records through template, validation, correction, and confirmation.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['csv', 'import', 'bulk import', 'template', 'validation'],
    routes: [{ label: 'Imports', href: '/imports' }],
    prerequisites: ['Required related records exist, such as departments before courses or academic cycles before sections.'],
    steps: [
      { label: 'Open import', detail: 'Open the relevant import flow and download or prepare the supported CSV template.' },
      { label: 'Upload file', detail: 'Upload CSV and run validation preview.' },
      { label: 'Fix errors', detail: 'Review invalid rows, required columns, unknown codes, and duplicate warnings.' },
      { label: 'Confirm import', detail: 'Confirm only after validation looks correct.' },
      { label: 'Review records', detail: 'Open the target module and verify imported records.' },
    ],
    warnings: ['Do not confirm imports with unresolved validation errors.'],
    relatedDocs: ['/docs/csv-imports', '/docs/identification-codes'],
  },
  {
    id: 'campus-space-manage',
    title: 'Campus space management',
    category: 'Setup',
    summary: 'Create buildings and rooms used by sections, schedules, and campus navigation.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN'],
    tags: ['building', 'room', 'campus', 'navigation', 'capacity'],
    routes: [
      { label: 'Buildings', href: '/buildings' },
      { label: 'Rooms', href: '/rooms' },
      { label: 'Campus Navigation', href: '/campus-navigation' },
    ],
    prerequisites: ['Department codes or building details are known if used.'],
    steps: [
      { label: 'Create building', detail: 'Open Buildings and add building name, code, address, image, landmark, and directions as needed.' },
      { label: 'Create rooms', detail: 'Open Rooms or building rooms and add room name, code, floor, type, capacity, and directions.' },
      { label: 'Attach defaults', detail: 'Use rooms as section defaults or schedule-specific rooms.' },
      { label: 'Verify navigation', detail: 'Open Campus Navigation to confirm users can find the room and directions.' },
    ],
    warnings: ['Room capacity warnings guide enrollment and scheduling but may not block every action.'],
    relatedDocs: ['/docs/departments-buildings-rooms', '/docs/campus-navigation'],
  },
  {
    id: 'ai-copilot-admin',
    title: 'EduVerse Copilot subscription and settings',
    category: 'EduVerse Copilot',
    summary: 'Manage organization Copilot plan, role access, credits, and usage.',
    roles: ['ORG_ADMIN'],
    tags: ['ai', 'copilot', 'subscription', 'credits', 'usage', 'role access'],
    routes: [
      { label: 'AI Subscription', href: '/ai/subscription' },
      { label: 'AI Usage', href: '/ai' },
      { label: 'Settings', href: '/settings' },
    ],
    prerequisites: ['Signed-in user is Org Admin for organization subscription and role access settings.'],
    steps: [
      { label: 'Open usage', detail: 'Open EduVerse Copilot usage dashboard to review credits and activity.' },
      { label: 'Manage plan', detail: 'Use View or Change Subscription to open /ai/subscription and select the organization plan.' },
      { label: 'Configure access', detail: 'In organization AI settings, enable or disable roles and assign monthly role credit policies.' },
      { label: 'Monitor usage', detail: 'Review credits used, remaining credits, trends, top users, feature usage, and estimated cost.' },
    ],
    warnings: ['Enabling students or guardians can increase AI Credit usage and subscription cost.'],
    relatedDocs: ['/docs/ai-copilot', '/docs/payments-billing'],
  },
  {
    id: 'personal-copilot-subscription',
    title: 'Personal Copilot subscription',
    category: 'EduVerse Copilot',
    summary: 'Use a personal Copilot plan when organization access is unavailable or credits are exhausted.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER', 'FINANCE_MANAGER', 'TEACHER', 'STUDENT', 'GUARDIAN'],
    tags: ['personal ai', 'copilot credits', 'top up', 'subscription'],
    routes: [
      { label: 'AI Subscription', href: '/ai/subscription' },
      { label: 'AI Usage', href: '/ai' },
    ],
    prerequisites: ['User is signed in and wants personal Copilot access.'],
    steps: [
      { label: 'Open subscription', detail: 'Open /ai/subscription from Copilot usage or the Copilot panel prompt.' },
      { label: 'Choose personal plan', detail: 'Select the personal plan tier that fits expected usage.' },
      { label: 'Complete checkout', detail: 'Finish the hosted checkout flow and return to EduVerse.' },
      { label: 'Review credits', detail: 'Open AI usage to confirm personal credits and current billing period.' },
    ],
    warnings: ['Personal subscription unlocks Copilot only for the purchasing user and never expands data permissions.'],
    relatedDocs: ['/docs/ai-copilot', '/docs/payments-billing'],
  },
  {
    id: 'account-security',
    title: 'Account security management',
    category: 'Support',
    summary: 'Manage password, sessions, linked accounts, and account security checks.',
    roles: ['ORG_ADMIN', 'SUB_ADMIN', 'ORG_MANAGER', 'FINANCE_MANAGER', 'TEACHER', 'STUDENT', 'GUARDIAN'],
    tags: ['password', 'security', 'sessions', 'linked accounts', 'login'],
    routes: [{ label: 'Settings', href: '/settings' }],
    prerequisites: ['User can access own account settings or admin account management where permitted.'],
    steps: [
      { label: 'Open account settings', detail: 'Open Settings or profile/account security area.' },
      { label: 'Update credentials', detail: 'Change password or linked account settings as needed.' },
      { label: 'Review sessions', detail: 'Review active sessions and revoke unknown sessions.' },
      { label: 'Verify login', detail: 'Sign in again when required and confirm the account remains accessible.' },
    ],
    warnings: ['Password changes and session revocation can force re-login on devices.'],
    relatedDocs: ['/docs/account-security'],
  },
];

export function buildAIFlowSearchEntries(): AIFlowSearchEntry[] {
  return aiFlows.map((flow) => {
    const routeText = flow.routes.map((route) => `${route.label} ${route.href}`).join(' ');
    const bodyText = [
      flow.title,
      flow.summary,
      flow.category,
      ...flow.prerequisites,
      ...flow.steps.flatMap((step) => [step.label, step.detail]),
      ...(flow.warnings ?? []),
      routeText,
    ].join(' ');

    return {
      ...flow,
      warnings: flow.warnings ?? [],
      relatedDocs: flow.relatedDocs ?? [],
      bodyText,
      tagText: flow.tags.join(' '),
      routeText,
    };
  });
}
