export const PLATFORM_NAME = 'EduVerse';

export const DASHBOARD_MODULES = [
    'overview',
    'admin',
    'teachers',
    'sub-admins',
    'finance-managers',
    'students',
    'mail',
    'settings',
    'announcements',
    'assessments',
    'timetable',
    'sections',
    'tasks',
    'chat',
    'change-password',
    'course-materials',
    'courses',
    'grades',
    'grade-finalization',
    'schedules',
    'attendance',
    'profile',
    'academic-cycles',
    'cohorts',
    'promotions',
    'transcripts',
    'finance',
    'fees',
];
